### ISSUE TITLE
Installation fails on Magisk v15.0

### ISSUE THREAD

**Issue by dodslaser** [Magisk-Modules-Repo/Wireguard-Magisk#1]
The installation fails with the following output on Magisk v15.0

```
- Copying zip to temp directory
- Installing Wireguard_installer-1.1.zip
- Mounting /system, /vendor
Archive:  /data/user/0/com.EWg.HJCyU1z.ojso/cache/install.zip
  inflating: common/post-fs-data.sh
  inflating: common/service.sh
  inflating: common/system.prop
  inflating: config.sh
  inflating: module.prop
update-binary[81]: [: -ge: missing second argument
*******************************
 Please install Magisk v15.0+! 
*******************************
Failed!
! Installation failed
```

**Comment by ryaniskira** [comment]
I am aware and looking into it now, someone already has a fix and submitted pull requests to two of my other modules to fix. I am going to see what he did and apply his fix to this one soon.

**Comment by ryaniskira** [comment]
I applied the fix and pushed it, try it again.

**Comment by zx2c4** [comment]
This functionality now lives in the WireGuard app itself. Please migrate away from this module and install the Magisk module from inside the app.


<img src="https://user-images.githubusercontent.com/10643/40954283-29235e2e-6884-11e8-8b89-75bb8641461a.png" width="300"><img src="https://user-images.githubusercontent.com/10643/40954285-2bb7e6be-6884-11e8-9be4-533b430ddcf3.png" width="300"><img src="https://user-images.githubusercontent.com/10643/40954287-2e28a92e-6884-11e8-82cd-6ff29a37aca2.png" width="300">
