### ISSUE TITLE
Not working on Nitrogen OS 8.1 on Nexus 6

### ISSUE THREAD

**Issue by MrDemous** [Magisk-Modules-Repo/Wireguard-Magisk#2]
I installed the module through Magisk 15.1 and when I try to turn a server on from the WireGuard app I get an error that the ROM doesn't support it.

I'm running Nitrogen OS 8.1 and ElementalX Kernel

ROM Link: https://forum.xda-developers.com/nexus-6/development/rom-nitrogen-os-n-substratum-11-10-2016-t3478365
Kernel Link: https://forum.xda-developers.com/nexus-6/orig-development/kernel-elementalx-n6-0-01-alpha-t2954680

**Comment by ryaniskira** [comment]
I don't think EX has Wireguard support. I know in the readme.md I stated "Preferably a kernel with Wireguard support" but that may be a requirement as there is no user space implementation on Android yet. If you drop into a shell, can you invoke wg or wg-quick?

**Comment by MrDemous** [comment]
Here

![screenshot_terminal_emulator_20171230-210430](https://user-images.githubusercontent.com/3586407/34456666-1eb9d4f4-eda5-11e7-8ef6-eae3a2ae41c5.png)

**Comment by ryaniskira** [comment]
I don't think you need to run su before running a command once you're root. I will look into this issue though.

**Comment by zx2c4** [comment]
This functionality now lives in the WireGuard app itself. Please migrate away from this module and install the Magisk module from inside the app.


<img src="https://user-images.githubusercontent.com/10643/40954283-29235e2e-6884-11e8-8b89-75bb8641461a.png" width="300"><img src="https://user-images.githubusercontent.com/10643/40954285-2bb7e6be-6884-11e8-9be4-533b430ddcf3.png" width="300"><img src="https://user-images.githubusercontent.com/10643/40954287-2e28a92e-6884-11e8-82cd-6ff29a37aca2.png" width="300">
