### ISSUE TITLE
Purpose?

### ISSUE THREAD

**Issue by zx2c4** [Magisk-Modules-Repo/Wireguard-Magisk#3]
I'm wondering what the purpose of this repo is. While it's cool to have something for Magisk, the latest app already has something called "Install command line tools" in settings which ships the latest version of the tools. Does this app feature obsolete this magisk module?

**Comment by ryaniskira** [comment]
The app feature writes to the system partition directly which will cause SafetyNet to fail. This module adds the binaries systemlessly so you can use Wireguard while retaining SafetyNet.
