### ISSUE TITLE
Commands don't work.

### ISSUE THREAD

**Issue by skittles9823** [Magisk-Modules-Repo/Wireguard-Magisk#4]
![?](https://i.imgur.com/clWUFsT.png)

Commands don't seem to be working.

**Comment by ryaniskira** [comment]
I am looking into it, and I am considering asking for help because it seems really hit or miss on whether the commands work or not.

**Comment by ryaniskira** [comment]
Interesting.

**Comment by skittles9823** [comment]
Yea, I thought so too.

**Comment by ryaniskira** [comment]
Unfortunately I'm getting slammed in school at the moment so I can't look into it much. If you can fix it feel free to do a pull request and I'll merge it.

**Comment by skittles9823** [comment]
I'll continue my attempts tomorrow and definitely will PR if I manage to fix it.
