### ISSUE TITLE
Not working, details below

### ISSUE THREAD

**Issue by MPeti1** [Magisk-Modules-Repo/Wireguard-Magisk#6]
Magisk Manager said it installed the module correctly, then i rebooted my phone and tried to turn on a configured interface in the Wireguard app. It says Wireguard kernel module is not installed. What's the problem?
I've first installed the module after version 1.1 released but didn't tried it out until now. I first simply updated the module to 1.2, then read the changelog and reinstalled the module (uninstall-reboot-install-reboot) .
Before the reinstall i installed the cli tools in the app, if that matters.

I have a Xiaomi Redmi 3S Prime with MIUI 8 7.6.15, and Magisk v15.3 with Manager 5.5.5

**Comment by MPeti1** [comment]
Maybe this issue can be merged to #2 , because the problem seems to be the same

**Comment by ryaniskira** [comment]
Oh I apologise I knew I was forgetting something. Wireguard has a Userspace implementation but apparently the Android app has not implemented it yet so you need kernel support for now.

**Comment by MPeti1** [comment]
Thanks for the fast reply :D is there an easy way to load its kernel module, or it's not how that's working?

**Comment by ryaniskira** [comment]
For Android the module has to be added to the kernel when compiled.

**Comment by MPeti1** [comment]
That's bad news :/ 1 year ago i tried to compile kernel for my phone because of some drivers, but i had no enough free storage space (about 30 GB) and also i don't really succeeded with cloning only the sources what i needed. even the repo init command always crashed with a python error speaking about too deep redundancy, so it can't be called a successful idea

**Comment by zx2c4** [comment]
This functionality now lives in the WireGuard app itself. Please migrate away from this module and install the Magisk module from inside the app.


<img src="https://user-images.githubusercontent.com/10643/40954283-29235e2e-6884-11e8-8b89-75bb8641461a.png" width="300"><img src="https://user-images.githubusercontent.com/10643/40954285-2bb7e6be-6884-11e8-9be4-533b430ddcf3.png" width="300"><img src="https://user-images.githubusercontent.com/10643/40954287-2e28a92e-6884-11e8-82cd-6ff29a37aca2.png" width="300">

**Comment by MPeti1** [comment]
I've just updated the app, but i can't find the option. Where is it?
I'm on v0.0.20180605

**Comment by zx2c4** [comment]
You don't have the kernel module on your phone, which means you could never use these tools anyway. They're not available for you and they never have been on that kernel.

**Comment by MPeti1** [comment]
Oh, I totally forgot that these are just the wg tools :D sorry
